version: "3"

services:
  frontend:
      image: habibo1234/investment-fe:2.0
      container_name: frontend
      ports:
          - 3000:3000
      restart: always
      depends_on:
        - backend

  backend:
    image: habibo1234/investment-be:6.0
    container_name: backend
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"