version: "3"
services:
  frontend:
      image: habibo1234/investment-fe:1.0
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend
  backend:
    image: habibo1234/investment-be:4.0
    restart: always
