version: "3"
services:
  frontend:
      image: frontend
      ports:
          - 8080:8080
      restart: always
      depends_on:
        - backend
  backend:
    image: investment-be
    Volumes:
      -/nginx/nginx-setup.config:/etc/nginx/conf.d/default.conf:ro
    environment:
      MYSQL_USERNAME: $MYSQL_USERNAME
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DB: $MYSQL_DB
      MYSQL_HOST: $MYSQL_HOST
