# .github/workflows/main.yml
#test
name: CI/CD Docker

on:
  push:
    branches:
      - staging
  pull_request:
    branches:
      - staging

jobs:
  Docker-Builds:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push Frontend Image 
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chiso1/stockapp-frontend:latest
          context: ./frontend
      -
        name: Build and push Backend Image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chiso1/stockapp-backend:latest
          context: ./backend

  Deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Git pull
        env:
          AWS_EC2_PEM: ${{ secrets.AWS_EC2_PEM  }}
          AWS_EC2_PUBLIC_IP: ${{ secrets.AWS_EC2_PUBLIC_IP  }}
          AWS_EC2_USERNAME: ${{ secrets.AWS_EC2_USERNAME  }}
        run: |
          pwd
          echo "$AWS_EC2_PEM" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${AWS_EC2_USERNAME}@${AWS_EC2_PUBLIC_IP} 
            cd ${GITHUB_WORKSPACE} && bash deploy.sh







